
# TELEGRAM CHAT IDs
TG_CHAT_ID_CHIVATAZOS = '-'
TG_CHAT_ID_DEV = ''
TG_CHAT_ID_TRIAL = ''

# TELEGRAM BOT TOKEN
TG_BOT_TOKEN = ''

# CUSTOMIZE
BOT_MIN_PROFIT = 10
BOT_MIN_RENTABILIDAD = 0.3
BOT_MIN_DIFFERENCE_PRICES = 0.5
BOT_BAN_PAIR_TIME = 15

# EXCHANGES ACTIVES
EX_BINANCE = True
EX_KUKOIN = False
EX_KRAKEN = True
EX_COINBASE = False

# LOG MESSAGES
BOT_VERSION = 'v2.6'
BOT_MESSAGE_START = f'AB {BOT_VERSION} started'
BOT_MESSAGE_RUNNING = f'AB {BOT_VERSION} active'
BOT_MESSAGE_STOP = f'AB {BOT_VERSION} stopped'
